import type { ItemResource } from "./ItemResource.ts"
import type { ResponseStatusDetails } from "./ResponseStatusDetails.ts"
import type { ResponseUsage } from "./ResponseUsage.ts"

export type ResponseResource = {
  /** The unique ID of the response. */
  id: string
  /** The object type. */
  object: "realtime.response"
  /** The status of the response. */
  status: "in_progress" | "completed" | "cancelled" | "failed" | "incomplete"
  /** Additional details about the status. */
  status_details: ResponseStatusDetails
  /** The list of output items generated by the response. */
  output: ItemResource[]
  /** Usage statistics for the response. */
  usage: ResponseUsage
}
